config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "homes#index"
get "contact_us" => 'homes#contact_us'

devise_for :users, controllers: { sessions: 'users/sessions' }

resources :restaurants do
	member do
		get :delete
	end
end

resources :users do
	member do
		get :delete
	end
end

resources :orders do
end


end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :menu


validates :quantity, presence: true, numericality: true

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  #before_action :authenticate_user!, except: [:index, :show]
  #before_action :set_restaurant, only: [:edit, :update, :destroy]
  #after_action :verify_authorized, except: [:index, :show] 
  #after_action :verify_policy_scoped, only: :index

  def index
      
  end

  def new
    #@restaurant = Restaurant.find(params[:id])
    @item = Menu.find(params[:menu_id])
    @order = @item.orders.build
  end

  def show
    @order = Order.all
   
  end

  def create
    #binding.pry
    #@restaurant = Restaurant.find(params[:id])
    @item = Menu.find(params[:menu_id])

    @order = @item.orders.build order_params
  
     #authorize @user
    if @order.save
    flash[:notice] = "Order Is Success"
      redirect_to(restaurants_path)
    else  
      render('new')
    end
  end

  def edit
  end

  def update
  
  end


  def delete

  end

  def menu_name
  @item = Menu.find(params[:menu_id])
  @name = @item.item

  end
  

  def order_params
  params.require(:order).permit(:menu_id,:quantity)

  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/new.html.erb
<h1>Order for <%= @item.item %></h1>

<%= form_for @order , url: orders_path(menu_id: @item.id) do |f| %>
<% if @order.errors.present? %>
<div class="alert alert-error"> <%=@order.errors.full_messages.to_sentence %> </div><%end%>

<div class="form-group">
	<%= f.label :quantity %> 
	<%= f.number_field :quantity, class: 'form-control' %>
</div>
<%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/orders/show.html.erb
<div class="col-sm-6">

<table class="table table-striped">ORDERS
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">menu_id</th>
      <th scope="col">Quantity</th>
      <th scope="col">Restaurant_id</th>
    </tr>
  </thead>
  <tbody>
	<% @order.each do |m| %>

    <tr>
      <th scope="row">1</th>
      <td><%= "#{m.menu_id}" %></td>
      <td><%= "#{m.quantity}" %></td>
       
    </tr>
    <%end%>
  </tbody>
</table>
 </div>