config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "homes#index"
get "contact_us" => 'homes#contact_us'

devise_for :users, controllers: { sessions: 'users/sessions' }

resources :restaurants do
	member do
		get :delete
	end
end

resources :users do
	member do
		get :delete
	end
end

resources :orders do
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
		@restaurants = Restaurant.all
		#@restaurants.order(:updated_at)
	end
	
	def contact_us
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/homes/contact_us.html.erb
<h1>Where We Are</h1>

<div class= "row">
<div class= "col-xs-3">
	<div class="card">
		<div class="class-header"><h3>Address</h3></div>
	</div>
	<div class="card-block">
		<address>
		Dhulikhel Road<br>
		Dhulikhel 45200
		</address>
		<p>Phone no: +977 9841000000 </p>
	</div>
</div>
<div class= "col-xs-9">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3535.265709268046!2d85.55629321507433!3d27.616286236094616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb09aa746e0009%3A0x7128307c0beff017!2sDhulikhel+Road%2C+Dhulikhel+45200!5e0!3m2!1sen!2snp!4v1517059148671" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

</div>
</div>

app/views/homes/index.html.erb
<! DOCTYPE html>
<html>

<!-- <div class="container">
	<div class="row">
		<div class="col-sm">
	<head>
	<title>"Foodmandu" %></title>
	<h1>Foodmandu</h1>
	</head>
	</div>
</div>
 -->
 <div class="container">
<div class="jumbotron">
  <h1 class="display-4">Find All The Best Restaurants In Town</h1>
  <p class="lead">People Who Love To Eat Are Always The Best People</p>
  <hr class="my-4">
  <p>Are you hungry?</p>
  <p class="lead">
    <%= link_to "Find Restaurants", restaurants_path,class: 'btn btn-primary btn-lg' %>
    <%= link_to "Contact Us", contact_us_path,class: 'btn btn-primary btn-lg' %>
  </p>
</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h3>Recently Added Member</h3>

			<p> </p>
		</div>

		<div class="col-sm-4">
		</div>
	</div>
		<div class="container">
	  <div class="row">
	  	<div class="col-sm-12">
				

				<% @restaurants.each do |r| %>
			    <div class="col-sm-4">
			    <div class="col-sm-4">
			     <%= link_to(image_tag(r.remote_image_url, width: '100px', height: '100px'), restaurant_path(r)) %>
			     </div>
			     <div class="col-sm-3">
			      <a><%= link_to("#{r.name}", restaurant_path(r), :class => 'action show') %></a>
			      <a><%= "#{r.location}" %></a>
			      <a><%= "#{r.cuisine}" %></a>			   
				</div>
			    </div>
				<% end %>
		   </div>
	  </div>

	  
	  	

	  
	</div>
</div>
		




	
</div>

<!-- before yield -->

<!-- after yield -->

</html>