config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "homes#index"
get "contact_us" => 'homes#contact_us'

devise_for :users, controllers: { sessions: 'users/sessions' }

resources :restaurants do
	member do
		get :delete
	end
end

resources :users do
	member do
		get :delete
	end
end

resources :orders do
end


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :user
	has_many :menus
	

	validates :name, :location, presence: true
	
	searchkick word_middle: [:name, :location]

	def search_data
		{
			name: name,
			location: location,
			cuisine: cuisine
		}
	end

	def remote_image_url
		if image_url.present?
			image_url
		else
			"https://loremflickr.com/320/240/#{CGI.escape name}"
		end
	end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :set_restaurant, only: [:edit, :update, :destroy]
  #after_action :verify_authorized, except: [:index, :show] 
  #after_action :verify_policy_scoped, only: :index

  def index
   #@restaurants = policy_scope(Restaurant).reverse
     #  if params[:query].present?
  #   @restaurants = Restaurant.search(params[:query], load: true)
  # # else
      search = params[:query].present? ? params[:query] : nil
      @restaurants = if search
      Restaurant.search(search, fields: [:location, :name, :cuisine] )
  
    else 
   @restaurants = Restaurant.paginate(:page => params[:page], :per_page => 2).order(:name)
  end
   @menus = Menu.all
   #end
    #@restaurants = Restaurant.all
  end

  def new
    #binding.pry

    @restaurant = current_user.restaurants.new
    
    #@restaurant = @user.restaurants.new
    authorize @restaurant
    #authorize @user
  end

  def create
    @restaurant = current_user.restaurants.create(restaurant_params)
    #@restaurant = Restaurant.create(restaurant_params)
    logger.debug @restaurant.errors.full_messages
    authorize @restaurant
    #authorize @user
    
    if @restaurant.save
      flash[:notice] = "Restaurant Added Successfully"
      redirect_to(restaurants_path)
    else 
      render('new')
    end
  end
  
  def show
    #binding.pry
    @restaurant = Restaurant.find(params[:id])
    @menu = @restaurant.menus
  end
  
  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    authorize @restaurant
    if @restaurant.update_attributes(restaurant_params)

    flash[:notice] = "Restaurant Updated Successfully"
    #redirect_to(pages_path)
    redirect_to(restaurants_path(@restaurant))
    else
      render('edit')
    end
  end


  def delete
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    flash[:notice] = "Restaurant Deleted Successfully"
    redirect_to(restaurants_path)

  end

  private
  def set_restaurant
    @resturant = Restaurant.find(params[:id])
    #authorize @restaurant
  end

  def restaurant_params
  params.require(:restaurant).permit(:name, :location, :cuisine, :service_charge, :vat, :contact,:user_id, :image_url,:utf8, :authenticity_token)

  end



end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/restaurants/_form.html.erb
<table summary="restaurant form fields">
	<tr>
		<th>Name</th>
		<td><%= f.text_field(:name) %> </td>
	</tr>
	<tr>
        <th> Location</th>
        <td><%= f.text_field(:location) %></td>
      </tr>
	<tr>
		<th>Cuisine</th>
		<td><%= f.text_field(:cuisine) %> </td>
	</tr>
	<tr>
		<th>Service Charge</th>
		<td><%= f.text_field(:service_charge) %> </td>
	</tr>
	<tr>
		<th>Vat</th>
		<td><%= f.text_field(:vat) %> </td>
	</tr>
	<tr>
		<th>Contact</th>
		<td><%= f.text_field(:contact) %> </td>
	</tr>

</table>

app/views/restaurants/create.html.erb
<h1>Restaurant#create</h1>
<p>Find me in app/views/restaurant/create.html.erb</p>

app/views/restaurants/delete.html.erb
<h1>Restaurant#delete</h1>
<p>Find me in app/views/restaurant/delete.html.erb</p>

app/views/restaurants/edit.html.erb
<!-- <h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>
 -->
 <%= link_to('<< Back to List', restaurants_path, :class => 'back-link') %>

 <div class="Restaurant edit">
 	<h2>Update Restaurant</h2>

<%= form_for(@restaurant) do |f| %>

<%= render(:partial => 'form', :locals => {:f => f}) %>

</table>

<div class="form button">
	<%= f.submit("Update Restaurant") %>
</div>

	 <% end%>
</div>

app/views/restaurants/index.html.erb
<! DOCTYPE html>
<html>

<div class="container">
	<head>
	<title>"Restaurant" %></title>
	<h3>Member Restaurant</h3>
	<p>Find restaurants of your choice from the list below and click 'Place Order' to continue.</p>
	<a><%= link_to("Add New Restaurant", new_restaurant_path, :class => 'action new') %></a>
	</head>
</div>

<div class="container">
<%= form_tag restaurants_path, method: :get do %>
<p>
	<%= text_field_tag :query, params[:query] %>
	<%= submit_tag "Search" , name: nil %>
</p>
<%end%>
</div>

<!-- <div class="table-responsive">
<table class="table">
<thead>
	<tr>
		<th>SN</th>
		<th>Name</th>
		<th>location</th>
		<th>cuisine</th>
		<th>service charge</th>
		<th>Vat</th>
		<th>contact</th>
	</tr>
</thead>
<tbody>
	<% @restaurants.each do |r| %>
	<tr>
		<td><%= r.id %></td>
		<td><%= r.name %></td>
		<td><%= r.location %> </td>
		<td><%= r.cuisine %> </td>
		<td><%= r.service_charge %></td>
		<td><%= r.vat %></td>
		<td><%= r.contact %></td>
	</tr>
	<% end%>

	</tbody>

</table>
</div>
 -->
	<div class="list-group">
				<% @restaurants.each do |r| %>
				<div class="list-group-item">
					<div class="card">
					<div class="class-header"><h3><%= link_to("#{r.name}", restaurant_path(r), :class => 'action show') %></h3>
					</div>
			     <%= link_to(image_tag(r.remote_image_url, width: '100px', height: '100px'), restaurant_path(r)) %>
			     </div>
				<div class="card-block">
			      <p><%= "located in #{r.location}" %></p>
			      <a><%= "cuisine: #{r.cuisine}" %></a>
			      <a><%= link_to("Show", restaurant_path(r), :class => 'action show') %></a>
				<a><%= link_to("Edit", edit_restaurant_path(r), :class => 'action edit') if policy(r).update? %></a> 
				<a><%= link_to("Delete", delete_restaurant_path(r), :class => 'action delete') if policy(r).delete?%></a>
				<% end %>
		   </div>

	  </div> 
	</div>

	
	<%= will_paginate @restaurants %>

<!-- </div>

<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h3></h3>
			<p> </p>
		</div>

		<div class="col-sm-4">
		</div>
	</div>
</div> -->

		
<!-- before yield -->

<!-- after yield -->

</html>

app/views/restaurants/new.html.erb
<%= link_to('<< Back to List', restaurants_path, :class => 'back-link') %>

 <div class="restaurant new">
 	<h2>Add A New Restaurant</h2>

<%= form_for(@restaurant)  do |f| %>

<% if @restaurant.errors.present? %>
<div class="alert alert-error"> <%=@restaurant.errors.full_messages.to_sentence %> </div><%end%>

<%= render(:partial => 'form', :locals => {:f => f}) %>


<div class="form button">
	<%= f.submit("Add Restaurant") %>
</div>

	 <% end%>
</div>
 

app/views/restaurants/show.html.erb
<div class="col-4">

 <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="..." alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

<div class="container">
<div class="col-sm-6">

<%= link_to("<< Back to List", restaurants_path, :class => 'back-list') %>
<h2><%= @restaurant.name%> </h2>
<p><%= "This restaurant is located in #{@restaurant.location} "%></p>
</div>

  </div>
<!-- </div> -->


<!-- <div class="col-12"> -->
<div class="col-sm-6">

<table class="table table-striped">MENU
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Item</th>
      <th scope="col">Price</th>
      <th scope="col">Order</th>
    </tr>
  </thead>
  <tbody>
	<% @menu.each do |m| %>

    <tr>
      <th scope="row">1</th>
      <td><%= "#{m.item}" %></td>
      <td><%= "#{m.price}" %></td>
      <td><%=link_to("Order",new_order_path(menu_id: m.id) )%></td>
    </tr>
    <%end%>
  </tbody>
</table>
 </div>

 